### ISSUE TITLE
implement custom recurrence 

### ISSUE THREAD

**Issue by ghost** [Zimbra-Community/Email-Reminder#1]
right now, we follow the Zimbra API, and implement, daily, weekly and so on.

While custom recurrence is a Zimbra feature, it is a lot of spaghetti code, and adds another dialog to the UI.

Doable, but a lot of work.

**Comment by xmjohn** [comment]
Bugzilla:
https://bugzilla.zimbra.com/show_bug.cgi?id=101503  Granular Calendar reminder time.

https://bugzilla.zimbra.com/show_bug.cgi?id=46502 Calendar Reminder Zimlet enhancements

**Comment by ghost** [comment]
Hello John,

I implemented granular reminder time as described in 101503. 
https://github.com/Zimbra-Community/com_zimbra_emailreminder/commit/66378e0163e0710730a0b79df63ce0c659580c79

I will release a new test version for this. However, it seems bug 101503 is invalid in 8.7.2, as one can type over the values suggested by Zimbra, so yes, there is `5 hours before`, and `10 hours before`.

You can just select one of those, and type over the 5, to make it a 6, 7 or whatever.

**Comment by ghost** [comment]
@xmjohn Maybe the `Number of minutes before an appointment to show reminder:` is more confusing than it does anything for most users.

Just check it out, if having the option of editing the appointment later and then customize the interval is enough. Maybe we should stick with the previous version.
